services:
  # Web Service
  - type: web
    name: faceauth
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python setup_render.py"
    startCommand: "gunicorn flogin.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: flogin.production_settings
      - key: DJANGO_DEBUG
        value: False
      - key: SECRET_KEY
        value: l*4+zwbw_%da#q-#jq6=o)@2u@ia-zbbq%!e1mcnc=s*0x9wfr

  # PostgreSQL Database
  - type: pserv
    name: faceauth-db
    plan: free
    env: postgres
